/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel A. Ardon E
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("caballoblanco.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_caballoBlanco.setIcon(imageIcon);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("reyblancoicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reyBlanco.setIcon(imageIcon1);
        ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("peonblancoicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_peonBlanco.setIcon(imageIcon2);
        ImageIcon imageIcon3 = new ImageIcon(new ImageIcon("reinablanca.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reinaBlanco.setIcon(imageIcon3);
        ImageIcon imageIcon4 = new ImageIcon(new ImageIcon("caballonegroicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_caballoNegro.setIcon(imageIcon4);
        ImageIcon imageIcon5 = new ImageIcon(new ImageIcon("reynegro.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reyNegro.setIcon(imageIcon5);
        ImageIcon imageIcon6 = new ImageIcon(new ImageIcon("peonnegro.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_peonNegro.setIcon(imageIcon6);
        ImageIcon imageIcon7 = new ImageIcon(new ImageIcon("reinanegra.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reinaNegro.setIcon(imageIcon7);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_caballoBlanco = new javax.swing.JLabel();
        lbl_reyBlanco = new javax.swing.JLabel();
        lbl_peonBlanco = new javax.swing.JLabel();
        lbl_reinaBlanco = new javax.swing.JLabel();
        lbl_reinaNegro = new javax.swing.JLabel();
        lbl_reyNegro = new javax.swing.JLabel();
        lbl_caballoNegro = new javax.swing.JLabel();
        lbl_peonNegro = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h7 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        e7 = new javax.swing.JLabel();
        e8 = new javax.swing.JLabel();
        f8 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        h8 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_movimiento = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Chess Oracle");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1136, 13, 153, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(176, 11, 12, 670);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pieces");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 11, 76, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 90, 30, 54);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 170, 30, 54);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 320, 30, 54);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("7");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 560, 33, 54);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 240, 30, 54);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("5");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 410, 30, 54);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("6");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 480, 33, 54);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(265, 11, 55, 54);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("8");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 650, 33, 54);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("D");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(549, 11, 55, 54);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("C");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 11, 55, 54);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("F");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(755, 11, 55, 54);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("E");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(656, 11, 55, 54);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("H");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(959, 11, 55, 54);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("G");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(860, 11, 55, 54);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("B");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(360, 11, 55, 54);

        lbl_caballoBlanco.setBackground(new java.awt.Color(0, 0, 0));
        lbl_caballoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_caballoBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_caballoBlancoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_caballoBlanco);
        lbl_caballoBlanco.setBounds(10, 71, 78, 141);

        lbl_reyBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_reyBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reyBlancoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_reyBlanco);
        lbl_reyBlanco.setBounds(98, 71, 74, 141);

        lbl_peonBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_peonBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_peonBlancoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_peonBlanco);
        lbl_peonBlanco.setBounds(10, 230, 78, 141);

        lbl_reinaBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_reinaBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reinaBlancoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_reinaBlanco);
        lbl_reinaBlanco.setBounds(94, 230, 78, 141);

        lbl_reinaNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_reinaNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reinaNegroMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_reinaNegro);
        lbl_reinaNegro.setBounds(94, 540, 78, 141);

        lbl_reyNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_reyNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reyNegroMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_reyNegro);
        lbl_reyNegro.setBounds(98, 381, 74, 141);

        lbl_caballoNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_caballoNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_caballoNegroMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_caballoNegro);
        lbl_caballoNegro.setBounds(10, 381, 78, 141);

        lbl_peonNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_peonNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_peonNegroMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_peonNegro);
        lbl_peonNegro.setBounds(10, 540, 78, 141);

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setForeground(new java.awt.Color(153, 0, 153));
        a2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a2.setOpaque(true);
        getContentPane().add(a2);
        a2.setBounds(240, 160, 88, 66);

        a1.setBackground(new java.awt.Color(0, 204, 204));
        a1.setForeground(new java.awt.Color(153, 0, 153));
        a1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a1.setOpaque(true);
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(240, 80, 88, 66);

        a4.setBackground(new java.awt.Color(255, 255, 255));
        a4.setForeground(new java.awt.Color(153, 0, 153));
        a4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a4.setOpaque(true);
        getContentPane().add(a4);
        a4.setBounds(240, 320, 88, 66);

        a3.setBackground(new java.awt.Color(0, 0, 0));
        a3.setForeground(new java.awt.Color(153, 0, 153));
        a3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a3.setOpaque(true);
        getContentPane().add(a3);
        a3.setBounds(240, 240, 88, 66);

        a6.setBackground(new java.awt.Color(255, 255, 255));
        a6.setForeground(new java.awt.Color(153, 0, 153));
        a6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a6.setOpaque(true);
        getContentPane().add(a6);
        a6.setBounds(240, 480, 88, 66);

        a5.setBackground(new java.awt.Color(0, 0, 0));
        a5.setForeground(new java.awt.Color(153, 0, 153));
        a5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a5.setOpaque(true);
        getContentPane().add(a5);
        a5.setBounds(240, 400, 88, 66);

        a8.setBackground(new java.awt.Color(255, 255, 255));
        a8.setForeground(new java.awt.Color(153, 0, 153));
        a8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a8.setOpaque(true);
        getContentPane().add(a8);
        a8.setBounds(240, 640, 88, 66);

        a7.setBackground(new java.awt.Color(0, 0, 0));
        a7.setForeground(new java.awt.Color(153, 0, 153));
        a7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a7.setOpaque(true);
        getContentPane().add(a7);
        a7.setBounds(240, 560, 88, 66);

        b8.setBackground(new java.awt.Color(0, 0, 0));
        b8.setForeground(new java.awt.Color(153, 0, 153));
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b8.setOpaque(true);
        getContentPane().add(b8);
        b8.setBounds(340, 640, 88, 66);

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setForeground(new java.awt.Color(153, 0, 153));
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b7.setOpaque(true);
        getContentPane().add(b7);
        b7.setBounds(340, 560, 88, 66);

        b6.setBackground(new java.awt.Color(0, 0, 0));
        b6.setForeground(new java.awt.Color(153, 0, 153));
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b6.setOpaque(true);
        getContentPane().add(b6);
        b6.setBounds(340, 480, 88, 66);

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setForeground(new java.awt.Color(153, 0, 153));
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b5.setOpaque(true);
        getContentPane().add(b5);
        b5.setBounds(340, 400, 88, 66);

        b4.setBackground(new java.awt.Color(0, 0, 0));
        b4.setForeground(new java.awt.Color(153, 0, 153));
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b4.setOpaque(true);
        getContentPane().add(b4);
        b4.setBounds(340, 320, 88, 66);

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setForeground(new java.awt.Color(153, 0, 153));
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b3.setOpaque(true);
        getContentPane().add(b3);
        b3.setBounds(340, 240, 88, 66);

        b2.setBackground(new java.awt.Color(0, 0, 0));
        b2.setForeground(new java.awt.Color(153, 0, 153));
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b2.setOpaque(true);
        getContentPane().add(b2);
        b2.setBounds(340, 160, 88, 66);

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setForeground(new java.awt.Color(153, 0, 153));
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b1.setOpaque(true);
        getContentPane().add(b1);
        b1.setBounds(340, 80, 88, 66);

        c8.setBackground(new java.awt.Color(255, 255, 255));
        c8.setForeground(new java.awt.Color(153, 0, 153));
        c8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c8.setOpaque(true);
        getContentPane().add(c8);
        c8.setBounds(440, 640, 88, 66);

        c7.setBackground(new java.awt.Color(0, 0, 0));
        c7.setForeground(new java.awt.Color(153, 0, 153));
        c7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c7.setOpaque(true);
        getContentPane().add(c7);
        c7.setBounds(440, 560, 88, 66);

        c6.setBackground(new java.awt.Color(255, 255, 255));
        c6.setForeground(new java.awt.Color(153, 0, 153));
        c6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c6.setOpaque(true);
        getContentPane().add(c6);
        c6.setBounds(440, 480, 88, 66);

        c5.setBackground(new java.awt.Color(0, 0, 0));
        c5.setForeground(new java.awt.Color(153, 0, 153));
        c5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c5.setOpaque(true);
        getContentPane().add(c5);
        c5.setBounds(440, 400, 88, 66);

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.setForeground(new java.awt.Color(153, 0, 153));
        c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c4.setOpaque(true);
        getContentPane().add(c4);
        c4.setBounds(440, 320, 88, 66);

        c3.setBackground(new java.awt.Color(0, 0, 0));
        c3.setForeground(new java.awt.Color(153, 0, 153));
        c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c3.setOpaque(true);
        getContentPane().add(c3);
        c3.setBounds(440, 240, 88, 66);

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setForeground(new java.awt.Color(153, 0, 153));
        c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c2.setOpaque(true);
        getContentPane().add(c2);
        c2.setBounds(440, 160, 88, 66);

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setForeground(new java.awt.Color(153, 0, 153));
        c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c1.setOpaque(true);
        getContentPane().add(c1);
        c1.setBounds(440, 80, 88, 66);

        d7.setBackground(new java.awt.Color(255, 255, 255));
        d7.setForeground(new java.awt.Color(153, 0, 153));
        d7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d7.setOpaque(true);
        getContentPane().add(d7);
        d7.setBounds(540, 560, 88, 66);

        d6.setBackground(new java.awt.Color(0, 0, 0));
        d6.setForeground(new java.awt.Color(153, 0, 153));
        d6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d6.setOpaque(true);
        getContentPane().add(d6);
        d6.setBounds(540, 480, 88, 66);

        d5.setBackground(new java.awt.Color(255, 255, 255));
        d5.setForeground(new java.awt.Color(153, 0, 153));
        d5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d5.setOpaque(true);
        getContentPane().add(d5);
        d5.setBounds(540, 400, 88, 66);

        d4.setBackground(new java.awt.Color(0, 0, 0));
        d4.setForeground(new java.awt.Color(153, 0, 153));
        d4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d4.setOpaque(true);
        getContentPane().add(d4);
        d4.setBounds(540, 320, 88, 66);

        d3.setBackground(new java.awt.Color(255, 255, 255));
        d3.setForeground(new java.awt.Color(153, 0, 153));
        d3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d3.setOpaque(true);
        getContentPane().add(d3);
        d3.setBounds(540, 240, 88, 66);

        d2.setBackground(new java.awt.Color(0, 0, 0));
        d2.setForeground(new java.awt.Color(153, 0, 153));
        d2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d2.setOpaque(true);
        getContentPane().add(d2);
        d2.setBounds(540, 160, 88, 66);

        d1.setBackground(new java.awt.Color(255, 255, 255));
        d1.setForeground(new java.awt.Color(153, 0, 153));
        d1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d1.setOpaque(true);
        getContentPane().add(d1);
        d1.setBounds(540, 80, 88, 66);

        d8.setBackground(new java.awt.Color(0, 0, 0));
        d8.setForeground(new java.awt.Color(153, 0, 153));
        d8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d8.setOpaque(true);
        getContentPane().add(d8);
        d8.setBounds(540, 640, 88, 66);

        e2.setBackground(new java.awt.Color(255, 255, 255));
        e2.setForeground(new java.awt.Color(153, 0, 153));
        e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e2.setOpaque(true);
        getContentPane().add(e2);
        e2.setBounds(640, 160, 88, 66);

        e1.setBackground(new java.awt.Color(0, 0, 0));
        e1.setForeground(new java.awt.Color(153, 0, 153));
        e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e1.setOpaque(true);
        getContentPane().add(e1);
        e1.setBounds(640, 80, 88, 66);

        e4.setBackground(new java.awt.Color(255, 255, 255));
        e4.setForeground(new java.awt.Color(153, 0, 153));
        e4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e4.setOpaque(true);
        getContentPane().add(e4);
        e4.setBounds(640, 320, 88, 66);

        e3.setBackground(new java.awt.Color(0, 0, 0));
        e3.setForeground(new java.awt.Color(153, 0, 153));
        e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e3.setOpaque(true);
        getContentPane().add(e3);
        e3.setBounds(640, 240, 88, 66);

        e5.setBackground(new java.awt.Color(0, 0, 0));
        e5.setForeground(new java.awt.Color(153, 0, 153));
        e5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e5.setOpaque(true);
        getContentPane().add(e5);
        e5.setBounds(640, 400, 88, 66);

        e6.setBackground(new java.awt.Color(255, 255, 255));
        e6.setForeground(new java.awt.Color(153, 0, 153));
        e6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e6.setOpaque(true);
        getContentPane().add(e6);
        e6.setBounds(640, 480, 88, 66);

        f6.setBackground(new java.awt.Color(0, 0, 0));
        f6.setForeground(new java.awt.Color(153, 0, 153));
        f6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f6.setOpaque(true);
        getContentPane().add(f6);
        f6.setBounds(740, 480, 88, 66);

        f5.setBackground(new java.awt.Color(255, 255, 255));
        f5.setForeground(new java.awt.Color(153, 0, 153));
        f5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f5.setOpaque(true);
        getContentPane().add(f5);
        f5.setBounds(740, 400, 88, 66);

        f4.setBackground(new java.awt.Color(0, 0, 0));
        f4.setForeground(new java.awt.Color(153, 0, 153));
        f4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f4.setOpaque(true);
        getContentPane().add(f4);
        f4.setBounds(740, 320, 88, 66);

        f3.setBackground(new java.awt.Color(255, 255, 255));
        f3.setForeground(new java.awt.Color(153, 0, 153));
        f3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f3.setOpaque(true);
        getContentPane().add(f3);
        f3.setBounds(740, 240, 88, 66);

        f2.setBackground(new java.awt.Color(0, 0, 0));
        f2.setForeground(new java.awt.Color(153, 0, 153));
        f2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f2.setOpaque(true);
        getContentPane().add(f2);
        f2.setBounds(740, 160, 88, 66);

        f1.setBackground(new java.awt.Color(255, 255, 255));
        f1.setForeground(new java.awt.Color(153, 0, 153));
        f1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f1.setOpaque(true);
        getContentPane().add(f1);
        f1.setBounds(740, 80, 88, 66);

        g6.setBackground(new java.awt.Color(255, 255, 255));
        g6.setForeground(new java.awt.Color(153, 0, 153));
        g6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g6.setOpaque(true);
        getContentPane().add(g6);
        g6.setBounds(840, 480, 88, 66);

        g5.setBackground(new java.awt.Color(0, 0, 0));
        g5.setForeground(new java.awt.Color(153, 0, 153));
        g5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g5.setOpaque(true);
        getContentPane().add(g5);
        g5.setBounds(840, 400, 88, 66);

        g4.setBackground(new java.awt.Color(255, 255, 255));
        g4.setForeground(new java.awt.Color(153, 0, 153));
        g4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g4.setOpaque(true);
        getContentPane().add(g4);
        g4.setBounds(840, 320, 88, 66);

        g3.setBackground(new java.awt.Color(0, 0, 0));
        g3.setForeground(new java.awt.Color(153, 0, 153));
        g3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g3.setOpaque(true);
        getContentPane().add(g3);
        g3.setBounds(840, 240, 88, 66);

        g2.setBackground(new java.awt.Color(255, 255, 255));
        g2.setForeground(new java.awt.Color(153, 0, 153));
        g2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g2.setOpaque(true);
        getContentPane().add(g2);
        g2.setBounds(840, 160, 88, 66);

        g1.setBackground(new java.awt.Color(0, 0, 0));
        g1.setForeground(new java.awt.Color(153, 0, 153));
        g1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g1.setOpaque(true);
        getContentPane().add(g1);
        g1.setBounds(840, 80, 88, 66);

        h6.setBackground(new java.awt.Color(0, 0, 0));
        h6.setForeground(new java.awt.Color(153, 0, 153));
        h6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h6.setOpaque(true);
        getContentPane().add(h6);
        h6.setBounds(940, 480, 88, 66);

        h5.setBackground(new java.awt.Color(255, 255, 255));
        h5.setForeground(new java.awt.Color(153, 0, 153));
        h5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h5.setOpaque(true);
        getContentPane().add(h5);
        h5.setBounds(940, 400, 88, 66);

        h4.setBackground(new java.awt.Color(0, 0, 0));
        h4.setForeground(new java.awt.Color(153, 0, 153));
        h4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h4.setOpaque(true);
        getContentPane().add(h4);
        h4.setBounds(940, 320, 88, 66);

        h3.setBackground(new java.awt.Color(255, 255, 255));
        h3.setForeground(new java.awt.Color(153, 0, 153));
        h3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h3.setOpaque(true);
        getContentPane().add(h3);
        h3.setBounds(940, 240, 88, 66);

        h2.setBackground(new java.awt.Color(0, 0, 0));
        h2.setForeground(new java.awt.Color(153, 0, 153));
        h2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h2.setOpaque(true);
        getContentPane().add(h2);
        h2.setBounds(940, 160, 88, 66);

        h1.setBackground(new java.awt.Color(255, 255, 255));
        h1.setForeground(new java.awt.Color(153, 0, 153));
        h1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h1.setOpaque(true);
        getContentPane().add(h1);
        h1.setBounds(940, 80, 88, 66);

        h7.setBackground(new java.awt.Color(255, 255, 255));
        h7.setForeground(new java.awt.Color(153, 0, 153));
        h7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h7.setOpaque(true);
        getContentPane().add(h7);
        h7.setBounds(940, 560, 88, 66);

        g7.setBackground(new java.awt.Color(0, 0, 0));
        g7.setForeground(new java.awt.Color(153, 0, 153));
        g7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g7.setOpaque(true);
        getContentPane().add(g7);
        g7.setBounds(840, 560, 88, 66);

        f7.setBackground(new java.awt.Color(255, 255, 255));
        f7.setForeground(new java.awt.Color(153, 0, 153));
        f7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f7.setOpaque(true);
        getContentPane().add(f7);
        f7.setBounds(740, 560, 88, 66);

        e7.setBackground(new java.awt.Color(0, 0, 0));
        e7.setForeground(new java.awt.Color(153, 0, 153));
        e7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e7.setOpaque(true);
        getContentPane().add(e7);
        e7.setBounds(640, 560, 88, 66);

        e8.setBackground(new java.awt.Color(255, 255, 255));
        e8.setForeground(new java.awt.Color(153, 0, 153));
        e8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e8.setOpaque(true);
        getContentPane().add(e8);
        e8.setBounds(640, 640, 88, 66);

        f8.setBackground(new java.awt.Color(0, 0, 0));
        f8.setForeground(new java.awt.Color(153, 0, 153));
        f8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f8.setOpaque(true);
        getContentPane().add(f8);
        f8.setBounds(740, 640, 88, 66);

        g8.setBackground(new java.awt.Color(255, 255, 255));
        g8.setForeground(new java.awt.Color(153, 0, 153));
        g8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        g8.setOpaque(true);
        getContentPane().add(g8);
        g8.setBounds(840, 640, 88, 66);

        h8.setBackground(new java.awt.Color(0, 0, 0));
        h8.setForeground(new java.awt.Color(153, 0, 153));
        h8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        h8.setOpaque(true);
        getContentPane().add(h8);
        h8.setBounds(940, 640, 88, 66);

        btn_clear.setText("Clear Chest Oracle");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(1180, 680, 140, 30);

        txta_movimiento.setColumns(20);
        txta_movimiento.setRows(5);
        txta_movimiento.setEnabled(false);
        jScrollPane1.setViewportView(txta_movimiento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1060, 100, 260, 200);

        jLabel12.setText("MOVIMIENTOS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1060, 80, 90, 14);

        setBounds(0, 0, 1341, 761);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_caballoBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_caballoBlancoMouseClicked
        // TODO add your handling code here:
        if (cont_caballoBlanco < 2) {
            lbl_caballoBlanco.setOpaque(true);
            lbl_caballoBlanco.setBackground(Color.red);
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de dos (2) Caballos");
            lbl_caballoBlanco.setOpaque(false);
            lbl_caballoBlanco.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_caballoBlancoMouseClicked

    private void lbl_reyBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reyBlancoMouseClicked
        // TODO add your handling code here:
        if (cont_reyBlanco < 1) {
            lbl_reyBlanco.setOpaque(true);
            lbl_reyBlanco.setBackground(Color.red);
            cont_reyBlanco++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de un (1) Rey!!");
            lbl_reyBlanco.setOpaque(false);
            lbl_reyBlanco.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_reyBlancoMouseClicked

    private void lbl_peonBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_peonBlancoMouseClicked
        // TODO add your handling code here:
        if (cont_peonBlanco < 8) {
            lbl_peonBlanco.setOpaque(true);
            lbl_peonBlanco.setBackground(Color.red);
            cont_peonBlanco++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de ocho (8) Peones!!");
            lbl_peonBlanco.setOpaque(false);
            lbl_peonBlanco.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_peonBlancoMouseClicked

    private void lbl_reinaBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reinaBlancoMouseClicked
        // TODO add your handling code here:
        if (cont_reinaBlanco < 1) {
            lbl_reinaBlanco.setOpaque(true);
            lbl_reinaBlanco.setBackground(Color.red);
            cont_reinaBlanco++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de una (1) Reina !!");
            lbl_reinaBlanco.setOpaque(false);
            lbl_reinaBlanco.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_reinaBlancoMouseClicked

    private void lbl_caballoNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_caballoNegroMouseClicked
        // TODO add your handling code here:
        if (cont_caballoNegro < 2) {
            lbl_caballoNegro.setOpaque(true);
            lbl_caballoNegro.setBackground(Color.red);
            cont_caballoNegro++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de dos (2) Caballos");
            lbl_caballoNegro.setOpaque(false);
            lbl_caballoNegro.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_caballoNegroMouseClicked

    private void lbl_reyNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reyNegroMouseClicked
        // TODO add your handling code here:
        if (cont_reyNegro < 1) {
            lbl_reyNegro.setOpaque(true);
            lbl_reyNegro.setBackground(Color.red);
            cont_reyNegro++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de un (1) Rey!!");
            lbl_reyNegro.setOpaque(false);
            lbl_reyNegro.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_reyNegroMouseClicked

    private void lbl_peonNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_peonNegroMouseClicked
        // TODO add your handling code here:
        if (cont_peonNegro < 8) {
            lbl_peonNegro.setOpaque(true);
            lbl_peonNegro.setBackground(Color.red);
            cont_peonNegro++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de ocho (8) Peones!!");
            lbl_peonNegro.setOpaque(false);
            lbl_peonNegro.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_peonNegroMouseClicked

    private void lbl_reinaNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reinaNegroMouseClicked
        // TODO add your handling code here:
        if (cont_reinaNegro < 1) {
            lbl_reinaNegro.setOpaque(true);
            lbl_reinaNegro.setBackground(Color.red);
            cont_reinaNegro++;
        } else {
            JOptionPane.showInternalMessageDialog(rootPane, "No se puede agregar mas de una (1) Reina!!");
            lbl_reinaNegro.setOpaque(false);
            lbl_reinaNegro.setBackground(Color.gray);
        }
    }//GEN-LAST:event_lbl_reinaNegroMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // TODO add your handling code here:
        //////// limpiar todo la A
        a1.setIcon(null);
        a1.revalidate();
        a2.setIcon(null);
        a2.revalidate();
        a3.setIcon(null);
        a3.revalidate();
        a4.setIcon(null);
        a4.revalidate();
        a5.setIcon(null);
        a5.revalidate();
        a6.setIcon(null);
        a6.revalidate();
        a7.setIcon(null);
        a7.revalidate();
        a8.setIcon(null);
        a8.revalidate();
        ///////////// limpiar toda la B
        b1.setIcon(null);
        b1.revalidate();
        b2.setIcon(null);
        b2.revalidate();
        b3.setIcon(null);
        b3.revalidate();
        b4.setIcon(null);
        b4.revalidate();
        b5.setIcon(null);
        b5.revalidate();
        b6.setIcon(null);
        b6.revalidate();
        b7.setIcon(null);
        b7.revalidate();
        b8.setIcon(null);
        b8.revalidate();
        //////////////// limpiar toda la C
        c1.setIcon(null);
        c1.revalidate();
        c2.setIcon(null);
        c2.revalidate();
        c3.setIcon(null);
        c3.revalidate();
        c4.setIcon(null);
        c4.revalidate();
        c5.setIcon(null);
        c5.revalidate();
        c6.setIcon(null);
        c6.revalidate();
        c7.setIcon(null);
        c7.revalidate();
        c8.setIcon(null);
        c8.revalidate();
        /////////////// limpiar toda la D
        d1.setIcon(null);
        d1.revalidate();
        d2.setIcon(null);
        d2.revalidate();
        d3.setIcon(null);
        d3.revalidate();
        d4.setIcon(null);
        d4.revalidate();
        d5.setIcon(null);
        d5.revalidate();
        d6.setIcon(null);
        d6.revalidate();
        d7.setIcon(null);
        d7.revalidate();
        d8.setIcon(null);
        d8.revalidate();
        /////////////limpiar toda la E
        e1.setIcon(null);
        e1.revalidate();
        e2.setIcon(null);
        e2.revalidate();
        e3.setIcon(null);
        e3.revalidate();
        e4.setIcon(null);
        e4.revalidate();
        e5.setIcon(null);
        e5.revalidate();
        e6.setIcon(null);
        e6.revalidate();
        e7.setIcon(null);
        e7.revalidate();
        e8.setIcon(null);
        e8.revalidate();
        /////////// limpiar toda la F
        f1.setIcon(null);
        f1.revalidate();
        f2.setIcon(null);
        f2.revalidate();
        f3.setIcon(null);
        f3.revalidate();
        f4.setIcon(null);
        f4.revalidate();
        f5.setIcon(null);
        f5.revalidate();
        f6.setIcon(null);
        f6.revalidate();
        f7.setIcon(null);
        f7.revalidate();
        f8.setIcon(null);
        f8.revalidate();
        /////////// limpiar toda la G
        g1.setIcon(null);
        g1.revalidate();
        g2.setIcon(null);
        g2.revalidate();
        g3.setIcon(null);
        g3.revalidate();
        g4.setIcon(null);
        g4.revalidate();
        g5.setIcon(null);
        g5.revalidate();
        g6.setIcon(null);
        g6.revalidate();
        g7.setIcon(null);
        g7.revalidate();
        g8.setIcon(null);
        g8.revalidate();
        ////////////// limpiar toda la H
        h1.setIcon(null);
        h1.revalidate();
        h2.setIcon(null);
        h2.revalidate();
        h3.setIcon(null);
        h3.revalidate();
        h4.setIcon(null);
        h4.revalidate();
        h5.setIcon(null);
        h5.revalidate();
        h6.setIcon(null);
        h6.revalidate();
        h7.setIcon(null);
        h7.revalidate();
        h8.setIcon(null);
        h8.revalidate();
        //////////// limpiar variables globales
        cont_caballoBlanco = 0;
        cont_reyBlanco = 0;
        cont_peonBlanco = 0;
        cont_reinaBlanco = 0;
        cont_caballoNegro = 0;
        cont_reyNegro = 0;
        cont_peonNegro = 0;
        cont_reinaNegro = 0;
        ///////////// limpiar la text area
        txta_movimiento.setText("");
    }//GEN-LAST:event_btn_clearMouseClicked

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
        if (lbl_caballoBlanco.isOpaque()) {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("caballoblanco.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_caballoBlanco.setOpaque(false);
            lbl_caballoBlanco.setBackground(Color.gray);
            cont_caballoBlanco++;
        }else if(lbl_reyBlanco.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("reyblancoicono.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_reyBlanco.setOpaque(false);
            lbl_reyBlanco.setBackground(Color.gray);
            cont_reyBlanco++;
        }else if(lbl_peonBlanco.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("peonblancoicono.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_peonBlanco.setOpaque(false);
            lbl_peonBlanco.setBackground(Color.gray);
            cont_peonBlanco++;
        }else if(lbl_reinaBlanco.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("reinablanco.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_reinaBlanco.setOpaque(false);
            lbl_reinaBlanco.setBackground(Color.gray);
            cont_reyBlanco++;
        }else if (lbl_caballoNegro.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("caballonegroicono.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_caballoNegro.setOpaque(false);
            lbl_caballoNegro.setBackground(Color.gray);
            cont_caballoNegro++;
        }else if(lbl_reyNegro.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("reynegro.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_reyNegro.setOpaque(false);
            lbl_reyNegro.setBackground(Color.gray);
            cont_reyNegro++;
        }else if(lbl_peonNegro.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("peonnegro.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_peonNegro.setOpaque(false);
            lbl_peonNegro.setBackground(Color.gray);
            cont_peonNegro++;
        }else if(lbl_reinaNegro.isOpaque()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("reinanegro.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            a1.setIcon(imageIcon);
            lbl_reinaNegro.setOpaque(false);
            lbl_reinaNegro.setBackground(Color.gray);
            cont_reinaNegro++;
        }
    }//GEN-LAST:event_a1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        lbl_caballoBlanco.setOpaque(false);
        lbl_caballoBlanco.setBackground(Color.gray);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel e7;
    private javax.swing.JLabel e8;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_caballoBlanco;
    private javax.swing.JLabel lbl_caballoNegro;
    private javax.swing.JLabel lbl_peonBlanco;
    private javax.swing.JLabel lbl_peonNegro;
    private javax.swing.JLabel lbl_reinaBlanco;
    private javax.swing.JLabel lbl_reinaNegro;
    private javax.swing.JLabel lbl_reyBlanco;
    private javax.swing.JLabel lbl_reyNegro;
    private javax.swing.JTextArea txta_movimiento;
    // End of variables declaration//GEN-END:variables
    private int cont_caballoBlanco = 0;
    private int cont_reyBlanco = 0;
    private int cont_peonBlanco = 0;
    private int cont_reinaBlanco = 0;
    private int cont_caballoNegro = 0;
    private int cont_reyNegro = 0;
    private int cont_peonNegro = 0;
    private int cont_reinaNegro = 0;
}
