/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Miguel A. Ardon E
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("caballoblanco.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_caballoBlanco.setIcon(imageIcon);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("reyblancoicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reyBlanco.setIcon(imageIcon1);
        ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("peonblancoicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_peonBlanco.setIcon(imageIcon2);
        ImageIcon imageIcon3 = new ImageIcon(new ImageIcon("reinablanca.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reinaBlanco.setIcon(imageIcon3);
        ImageIcon imageIcon4 = new ImageIcon(new ImageIcon("caballonegroicono.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_caballoNegro.setIcon(imageIcon4);
        ImageIcon imageIcon5 = new ImageIcon(new ImageIcon("reynegro.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reyNegro.setIcon(imageIcon5);
        ImageIcon imageIcon6 = new ImageIcon(new ImageIcon("peonnegro.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_peonNegro.setIcon(imageIcon6);
        ImageIcon imageIcon7 = new ImageIcon(new ImageIcon("reinanegra.png").getImage().getScaledInstance(78, 140, Image.SCALE_DEFAULT));
        lbl_reinaNegro.setIcon(imageIcon7);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_caballoBlanco = new javax.swing.JLabel();
        lbl_reyBlanco = new javax.swing.JLabel();
        lbl_peonBlanco = new javax.swing.JLabel();
        lbl_reinaBlanco = new javax.swing.JLabel();
        lbl_reinaNegro = new javax.swing.JLabel();
        lbl_reyNegro = new javax.swing.JLabel();
        lbl_caballoNegro = new javax.swing.JLabel();
        lbl_peonNegro = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Chess Oracle");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1136, 13, 153, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(176, 11, 12, 670);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pieces");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 11, 76, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("8");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(192, 71, 13, 54);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("7");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(192, 151, 13, 54);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(192, 311, 13, 54);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(192, 551, 33, 54);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(192, 231, 13, 54);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(192, 391, 13, 54);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(192, 471, 33, 54);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(265, 11, 55, 54);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(192, 631, 33, 54);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("D");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(549, 11, 55, 54);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("C");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 11, 55, 54);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("F");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(755, 11, 55, 54);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("E");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(656, 11, 55, 54);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("H");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(959, 11, 55, 54);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("G");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(860, 11, 55, 54);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("B");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(360, 11, 55, 54);

        lbl_caballoBlanco.setBackground(new java.awt.Color(0, 0, 0));
        lbl_caballoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_caballoBlanco);
        lbl_caballoBlanco.setBounds(10, 71, 78, 141);

        lbl_reyBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_reyBlanco);
        lbl_reyBlanco.setBounds(98, 71, 74, 141);

        lbl_peonBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_peonBlanco);
        lbl_peonBlanco.setBounds(10, 230, 78, 141);

        lbl_reinaBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_reinaBlanco);
        lbl_reinaBlanco.setBounds(94, 230, 78, 141);

        lbl_reinaNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_reinaNegro);
        lbl_reinaNegro.setBounds(94, 540, 78, 141);

        lbl_reyNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_reyNegro);
        lbl_reyNegro.setBounds(98, 381, 74, 141);

        lbl_caballoNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_caballoNegro);
        lbl_caballoNegro.setBounds(10, 381, 78, 141);

        lbl_peonNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lbl_peonNegro);
        lbl_peonNegro.setBounds(10, 540, 78, 141);

        a7.setBackground(new java.awt.Color(255, 255, 255));
        a7.setForeground(new java.awt.Color(153, 0, 153));
        a7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a7.setOpaque(true);
        getContentPane().add(a7);
        a7.setBounds(240, 160, 88, 66);

        a8.setBackground(new java.awt.Color(0, 0, 0));
        a8.setForeground(new java.awt.Color(153, 0, 153));
        a8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a8.setOpaque(true);
        getContentPane().add(a8);
        a8.setBounds(240, 80, 88, 66);

        a5.setBackground(new java.awt.Color(255, 255, 255));
        a5.setForeground(new java.awt.Color(153, 0, 153));
        a5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a5.setOpaque(true);
        getContentPane().add(a5);
        a5.setBounds(240, 320, 88, 66);

        a6.setBackground(new java.awt.Color(0, 0, 0));
        a6.setForeground(new java.awt.Color(153, 0, 153));
        a6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a6.setOpaque(true);
        getContentPane().add(a6);
        a6.setBounds(240, 240, 88, 66);

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setForeground(new java.awt.Color(153, 0, 153));
        a3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a3.setOpaque(true);
        getContentPane().add(a3);
        a3.setBounds(240, 480, 88, 66);

        a4.setBackground(new java.awt.Color(0, 0, 0));
        a4.setForeground(new java.awt.Color(153, 0, 153));
        a4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a4.setOpaque(true);
        getContentPane().add(a4);
        a4.setBounds(240, 400, 88, 66);

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setForeground(new java.awt.Color(153, 0, 153));
        a1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a1.setOpaque(true);
        getContentPane().add(a1);
        a1.setBounds(240, 640, 88, 66);

        a2.setBackground(new java.awt.Color(0, 0, 0));
        a2.setForeground(new java.awt.Color(153, 0, 153));
        a2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a2.setOpaque(true);
        getContentPane().add(a2);
        a2.setBounds(240, 560, 88, 66);

        b1.setBackground(new java.awt.Color(0, 0, 0));
        b1.setForeground(new java.awt.Color(153, 0, 153));
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b1.setOpaque(true);
        getContentPane().add(b1);
        b1.setBounds(340, 640, 88, 66);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setForeground(new java.awt.Color(153, 0, 153));
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b2.setOpaque(true);
        getContentPane().add(b2);
        b2.setBounds(340, 560, 88, 66);

        b3.setBackground(new java.awt.Color(0, 0, 0));
        b3.setForeground(new java.awt.Color(153, 0, 153));
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b3.setOpaque(true);
        getContentPane().add(b3);
        b3.setBounds(340, 480, 88, 66);

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setForeground(new java.awt.Color(153, 0, 153));
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b4.setOpaque(true);
        getContentPane().add(b4);
        b4.setBounds(340, 400, 88, 66);

        b5.setBackground(new java.awt.Color(0, 0, 0));
        b5.setForeground(new java.awt.Color(153, 0, 153));
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b5.setOpaque(true);
        getContentPane().add(b5);
        b5.setBounds(340, 320, 88, 66);

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setForeground(new java.awt.Color(153, 0, 153));
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b6.setOpaque(true);
        getContentPane().add(b6);
        b6.setBounds(340, 240, 88, 66);

        b7.setBackground(new java.awt.Color(0, 0, 0));
        b7.setForeground(new java.awt.Color(153, 0, 153));
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b7.setOpaque(true);
        getContentPane().add(b7);
        b7.setBounds(340, 160, 88, 66);

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setForeground(new java.awt.Color(153, 0, 153));
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b8.setOpaque(true);
        getContentPane().add(b8);
        b8.setBounds(340, 80, 88, 66);

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setForeground(new java.awt.Color(153, 0, 153));
        c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c1.setOpaque(true);
        getContentPane().add(c1);
        c1.setBounds(440, 640, 88, 66);

        c2.setBackground(new java.awt.Color(0, 0, 0));
        c2.setForeground(new java.awt.Color(153, 0, 153));
        c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c2.setOpaque(true);
        getContentPane().add(c2);
        c2.setBounds(440, 560, 88, 66);

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setForeground(new java.awt.Color(153, 0, 153));
        c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c3.setOpaque(true);
        getContentPane().add(c3);
        c3.setBounds(440, 480, 88, 66);

        c4.setBackground(new java.awt.Color(0, 0, 0));
        c4.setForeground(new java.awt.Color(153, 0, 153));
        c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c4.setOpaque(true);
        getContentPane().add(c4);
        c4.setBounds(440, 400, 88, 66);

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setForeground(new java.awt.Color(153, 0, 153));
        c5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c5.setOpaque(true);
        getContentPane().add(c5);
        c5.setBounds(440, 320, 88, 66);

        c6.setBackground(new java.awt.Color(0, 0, 0));
        c6.setForeground(new java.awt.Color(153, 0, 153));
        c6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c6.setOpaque(true);
        getContentPane().add(c6);
        c6.setBounds(440, 240, 88, 66);

        c7.setBackground(new java.awt.Color(255, 255, 255));
        c7.setForeground(new java.awt.Color(153, 0, 153));
        c7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c7.setOpaque(true);
        getContentPane().add(c7);
        c7.setBounds(440, 160, 88, 66);

        c8.setBackground(new java.awt.Color(0, 0, 0));
        c8.setForeground(new java.awt.Color(153, 0, 153));
        c8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c8.setOpaque(true);
        getContentPane().add(c8);
        c8.setBounds(440, 80, 88, 66);

        d2.setBackground(new java.awt.Color(255, 255, 255));
        d2.setForeground(new java.awt.Color(153, 0, 153));
        d2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d2.setOpaque(true);
        getContentPane().add(d2);
        d2.setBounds(540, 560, 88, 66);

        d3.setBackground(new java.awt.Color(0, 0, 0));
        d3.setForeground(new java.awt.Color(153, 0, 153));
        d3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d3.setOpaque(true);
        getContentPane().add(d3);
        d3.setBounds(540, 480, 88, 66);

        d4.setBackground(new java.awt.Color(255, 255, 255));
        d4.setForeground(new java.awt.Color(153, 0, 153));
        d4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d4.setOpaque(true);
        getContentPane().add(d4);
        d4.setBounds(540, 400, 88, 66);

        d5.setBackground(new java.awt.Color(0, 0, 0));
        d5.setForeground(new java.awt.Color(153, 0, 153));
        d5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d5.setOpaque(true);
        getContentPane().add(d5);
        d5.setBounds(540, 320, 88, 66);

        d6.setBackground(new java.awt.Color(255, 255, 255));
        d6.setForeground(new java.awt.Color(153, 0, 153));
        d6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d6.setOpaque(true);
        getContentPane().add(d6);
        d6.setBounds(540, 240, 88, 66);

        d7.setBackground(new java.awt.Color(0, 0, 0));
        d7.setForeground(new java.awt.Color(153, 0, 153));
        d7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d7.setOpaque(true);
        getContentPane().add(d7);
        d7.setBounds(540, 160, 88, 66);

        d8.setBackground(new java.awt.Color(255, 255, 255));
        d8.setForeground(new java.awt.Color(153, 0, 153));
        d8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d8.setOpaque(true);
        getContentPane().add(d8);
        d8.setBounds(540, 80, 88, 66);

        d1.setBackground(new java.awt.Color(0, 0, 0));
        d1.setForeground(new java.awt.Color(153, 0, 153));
        d1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d1.setOpaque(true);
        getContentPane().add(d1);
        d1.setBounds(540, 640, 88, 66);

        setBounds(0, 0, 1341, 761);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_caballoBlanco;
    private javax.swing.JLabel lbl_caballoNegro;
    private javax.swing.JLabel lbl_peonBlanco;
    private javax.swing.JLabel lbl_peonNegro;
    private javax.swing.JLabel lbl_reinaBlanco;
    private javax.swing.JLabel lbl_reinaNegro;
    private javax.swing.JLabel lbl_reyBlanco;
    private javax.swing.JLabel lbl_reyNegro;
    // End of variables declaration//GEN-END:variables
}
